# Generated by Django 5.0.1 on 2024-01-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('product_price', models.IntegerField(verbose_name='цена за штуку')),
                ('product_date', models.DateTimeField(verbose_name='дата создания')),
                ('product_last_modified', models.DateTimeField(verbose_name='дата последнего изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='в наличии')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
