# Generated by Django 5.0.1 on 2024-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_is_published',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
