# Generated by Django 5.0.1 on 2024-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_blog_blog_is_published_alter_blog_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_vers', models.CharField(max_length=100, verbose_name='продукт версии')),
                ('version_name', models.TextField(max_length=500, verbose_name='название версии')),
                ('version_number', models.IntegerField(verbose_name='номер версии')),
                ('vers_is_active', models.BooleanField(default=True, verbose_name='признак текущей версии')),
            ],
            options={
                'verbose_name': 'продукт версии',
                'verbose_name_plural': 'продукты версии',
                'ordering': ('product_vers',),
            },
        ),
    ]
