# Generated by Django 5.0.1 on 2024-03-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_product_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_published',
            field=models.BooleanField(default=False, verbose_name='опубликован'),
        ),
    ]
